services:
  orchestrator:
    build:
      dockerfile: Dockerfile
    container_name: orchestrator
    environment:
      ORCHESTRATOR_CONFIG_PATH: /opt/config.yml
      ORCHESTRATOR_DATA_PATH: ${ORCHESTRATOR_DATA_PATH:-/opt/data}
    ports:
      - "3000:3000"
    volumes:
      - ./config.yaml:/opt/config.yml
      - orchestrator-wd-data:${ORCHESTRATOR_DATA_PATH:-/opt/data}
    networks:
      - api
      - public

  jobd:
    image: ghcr.io/rvhonorato/jobd:v0.1.0
    container_name: jobd
    environment:
      DEBUG: true
    networks:
      - api

networks:
  public:
    internal: false
  api:
    internal: true

volumes:
  orchestrator-wd-data:
