services:
  orchestrator:
    build:
      dockerfile: deployment/orchestrator.Dockerfile
    container_name: orchestrator
    environment:
      # Location inside the container where the data will be saved
      DATA_PATH: /opt/data
      # Location inside the container where the db will be saved
      DB_PATH: /opt/data/db.sqlite
      # Max age of folders (in seconds)
      MAX_AGE: 172800
      # Services #==================================================#
      SERVICE_GENERIC_UPLOAD_URL: http://generic:8888/api/upload
      SERVICE_GENERIC_DOWNLOAD_URL: http://generic:8888/api/get
      SERVICE_GENERIC_RUNS_PER_USER: 5
      #=============================================================#
    ports:
      - "5000:5000"
    volumes:
      - orchestrator-data:/opt/data
    networks:
      - api
      - public

  generic:
    build:
      dockerfile: deployment/generic.Dockerfile
    container_name: generic
    command: /bin/jobd
    environment:
      PORT: 8888
      DEBUG: true
    ports:
      - 8888:8888
    networks:
      - api

networks:
  public:
    internal: false
  api:
    internal: true

volumes:
  orchestrator-data:
